version: '3'

services:
  airflow:
    build: .
    container_name: car_sales_airflow
    restart: always
    ports:
      - "5000:5000"

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - 8499:8499
    command: 
      - "postgres"
      - "-p"
      - "8499"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always
  minio:
    container_name: car_sales_data_lake
    restart: always
    image: minio/minio
    env_file:
      - ./.env
    volumes:
      - data_lake:/data
    ports:
      - 9000:9000
    networks:
      mynetwork:
        ipv4_address: 172.16.238.10
    command: server --console-address ":9001" /data

networks:
  mynetwork:
    ipam:
      config:
        - subnet: "172.16.238.0/24"
volumes:
  postgres_data:
  data_lake: